version: "3.8"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: ${DOCKER_USERNAME:-xanderbilla}/devops-backend:${IMAGE_TAG:-latest}
    container_name: backend
    ports:
      - "8500:8500"
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/devopsdb
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:8500/health || exit 1",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  frontend:
    image: ${DOCKER_USERNAME:-xanderbilla}/devops-frontend:${IMAGE_TAG:-latest}
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8500
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data:
