services:
  backend:
    image: ${DOCKER_USERNAME:-xanderbilla}/devops-backend:${IMAGE_TAG:-latest}
    ports:
      - "8500:8080"
    networks:
      - app-network
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "wget --no-verbose --tries=1 --spider http://localhost:8080/actuator/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

  frontend:
    image: ${DOCKER_USERNAME:-xanderbilla}/devops-frontend:${IMAGE_TAG:-latest}
    ports:
      - "3000:80"
    depends_on:
      - backend
    # environment:
    #   - NEXT_PUBLIC_API_URL=http://${JENKINS_HOST:-localhost}:8500
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager

networks:
  app-network:
    driver: overlay
    attachable: true

volumes:
  mongo-data:
    driver: local
