version: "3.8"

services:
  mongo:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: xanderbilla/devops-backend::${IMAGE_TAG}
    ports:
      - "8500:8500"
    depends_on:
      - mongo
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/devopsdb
    networks:
      - app-network

  frontend:
    image: xanderbilla/devops-frontend::${IMAGE_TAG}
    ports:
      - "3000:80"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8500
    networks:
      - app-network

networks:
  app-network:
    driver: overlay

volumes:
  mongo-data: